# Generated by Django 5.0.7 on 2024-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Сеть', 'verbose_name_plural': 'Сети'},
        ),
        migrations.AlterField(
            model_name='network',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
