# Generated by Django 5.0.7 on 2024-07-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_network_options_alter_network_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
